  name: BedwarsPlugin
  main: at.fabiadam.main.MainBedwars
  version: 1.0
  api-version: 1.19

  commands:
    start:
      description: Used to start a round of bedwars before the timer counts to zero
      usage: /start
    bw:
      description: General command for all bedwars related commands
      usage: /bw <command>